
"use client"
import { useState } from "react"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Button } from "@/components/ui/button"
import { Place } from "@/db/places"


export default function PosPage(
    { posId,
        places

    }:
        {
            posId: string,
            places: Place[] | null
        }
) {
    const [name, setName] = useState("")

    return (
        <div className="flex min-h-screen items-center justify-center p-4">
            <Card className="w-full max-w-sm mx-auto">
                <CardHeader>
                    <CardTitle>Activate Your Point of Sales App</CardTitle>

                </CardHeader>
                <CardContent className="space-y-4">
                    <div className="space-y-2">
                        <Label htmlFor="place">Assign to a place</Label>
                        <Select defaultValue={places?.[0]?.id.toString() ?? ''}>
                            <SelectTrigger id="place">
                                <SelectValue placeholder="Select a place" />
                            </SelectTrigger>
                            <SelectContent>
                                {places &&  places?.map((place) => (
                                    <SelectItem key={place.id} value={place.id.toString()}>
                                        {place.name}
                                    </SelectItem>
                                ))}

                            </SelectContent>
                        </Select>
                        <p className="text-sm text-muted-foreground">
                            This will assign all orders generated by your app to this place.
                        </p>
                    </div>

                    <div className="space-y-2">
                        <Label htmlFor="name">Name</Label>
                        <Input id="name" placeholder="Enter name" value={name} onChange={(e) => setName(e.target.value)} />
                    </div>
                </CardContent>
                <CardFooter>
                    <Button
                        className="w-full"
                        disabled={!name.trim()}
                        onClick={() => console.log("Activating POS with name:", name)}
                    >
                        Activate POS
                    </Button>
                </CardFooter>
            </Card>
        </div>
    )
}

